<a href="https://colab.research.google.com/github/VidhiSidana/UCS420/blob/main/assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [2]:
temperature_corrected = temperature + 2
print(temperature_corrected)

[27 30 33 37 40 29 35 42]


In [3]:
fahrenheit = (temperature_corrected * 9/5) + 32
print(fahrenheit)

[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


In [4]:
greater_than_32 = temperature_corrected[temperature_corrected > 32]
print(greater_than_32)

[33 37 40 35 42]


In [5]:
count = np.sum(temperature_corrected > 32)
print(count)

5


In [6]:
temperature_corrected > 32

array([False, False,  True,  True,  True, False,  True,  True])

In [7]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

In [8]:
total_steps = np.sum(steps)
print(total_steps)

Total steps: 84200


In [9]:
mean_steps = np.mean(steps)
print( mean_steps)

7016.666666666667


In [10]:
day_total = np.sum(steps, axis=0)
print(day_total)

[26500 27300 30400]


In [11]:
user_total = np.sum(steps, axis=1)
print(user_total)

[18300 24500 14400 27000]


In [12]:
max_index = np.argmax(steps)
print(max_index)
position = np.unravel_index(np.argmax(steps), steps.shape)
print(position)

11
(np.int64(3), np.int64(2))


In [13]:
original = np.array([1, 2, 3, 4, 5, 6])
print(original)

[1 2 3 4 5 6]


In [14]:
subset = original[1:5]
print(subset)

[2 3 4 5]


In [15]:
subset[0] = 999
print("Original:", original)
print("Subset:", subset)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


In [16]:
copied_array = original[1:5].copy()
copied_array[0] = 500
print("Original:", original)
print("Copied array:", copied_array)

Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]


In [17]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
print(matrix[0, :])

[1 2 3 4]


In [23]:
print(matrix[-1, :])

[ 9 10 11 12]


In [24]:
print(matrix[:, 1])

[ 2  6 10]


In [25]:

print(matrix[0:2, 1:3])

[[2 3]
 [6 7]]


In [26]:
flat_array = matrix.flatten()
ravel_array = matrix.ravel()
print(flat_array)
print(ravel_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
matrix = np.arange(1, 13).reshape(3, 4)
flat_array = matrix.flatten()
flat_array[0] = 500
print("Flatten array:", flat_array)
print("Original matrix:")
print(matrix)

Flatten array: [500   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [29]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)
print("\nX transpose:")
print(X.T)
XtX = X.T @ X
print("\nX.T @ X:")
print(XtX)
XtX_inv = np.linalg.inv(XtX)

print("\nInverse of X.T @ X:")
print(XtX_inv)
beta = XtX_inv @ X.T @ y

print("\nOLS coefficients:")
print(beta)
print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nPredicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

X transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

Predicted assistance score: 75.27862544779117


In [30]:
new_user = np.array([5, 40, 7])

In [31]:
predicted_score = new_user @ beta