<a href="https://colab.research.google.com/github/VidhiSidana/UCS420/blob/main/assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print( arr)
print(arr + 2)
print(arr * 3)
print(arr / 2)

[10 20 30 40 50]
[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print( arr)
print(arr[::-1])

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(x, return_counts=True)
most_frequent_x = values[np.argmax(counts)]
indices_x = np.where(x == most_frequent_x)[0]

print(x)
print("Most frequent value in x:", most_frequent_x)
print("Indices:", indices_x)
values, counts = np.unique(y, return_counts=True)
most_frequent_y = values[np.argmax(counts)]
indices_y = np.where(y == most_frequent_y)[0]
print(y)
print("Most frequent value in y:", most_frequent_y)
print("Indices:", indices_y)

[1 2 3 4 5 1 2 1]
Most frequent value in x: 1
Indices: [0 5 7]
[1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices: [0 1 2]


In [5]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [6]:
print(arr[0, 1])

20


In [7]:
print(arr[2, 0])

70


In [8]:
import numpy as np
vidhi = np.linspace(10, 100, 25)
print(vidhi)
print("Dimensions:", vidhi.ndim)
print("Shape:", vidhi.shape)
print("Total elements:", vidhi.size)
print("Data type:", vidhi.dtype)
print("Total bytes:", vidhi.nbytes)
print("Transpose:", vidhi.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
import numpy as np
ucs420_vidhi = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_vidhi)
print("\nMean:", np.mean(ucs420_vidhi))
print("Median:", np.median(ucs420_vidhi))
print("Maximum:", np.max(ucs420_vidhi))
print("Minimum:", np.min(ucs420_vidhi))
resized_ucs420_vidhi = ucs420_vidhi.reshape(4, 3)
print(resized_ucs420_vidhi)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
